import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const properties = [
  {name:'Zenith Peak Penthouse', location:'90210 Beverly Hills, CA', price:'$3,450,000', match:'98%', rating:'4.9', beds:'4 BHK', area:'4,850 sqft', image:'/images/property-details.png'},
  {name:'Aura Ocean Vista', location:'Malibu Cliffs, CA', price:'$5,200,000', match:'95%', rating:'4.8', beds:'5 BHK', area:'6,120 sqft', image:'/images/property-search.png'},
  {name:'Canyon Lodge Oasis', location:'Aspen Heights, CO', price:'$1,980,000', match:'91%', rating:'4.7', beds:'3 BHK', area:'3,200 sqft', image:'/images/home-reference.png'}
];

function Header(){return <header className="header"><div className="logo"><span>Q</span> HomiQ</div><nav><span>Home</span><span>Properties</span><span>AI Recommendation</span><span>Virtual Tours</span><span>Services</span><span>About</span></nav><div className="auth"><span>Login</span><button>Get Started</button></div></header>}
function Footer(){return <footer><div className="footerTop"><div><div className="logo light"><span>Q</span> HomiQ</div><p>Transforming the premium real estate journey<br/>with predictive intelligence, deep property<br/>verification, and cinematic VR tours.</p></div><div><h4>Platform</h4><p>AI Search</p><p>Virtual 360° Tours</p><p>Verification Suite</p></div><div><h4>Company</h4><p>About Us</p><p>Our Experts</p><p>Contact & Support</p></div><div><h4>Trust & Security</h4><p>Secure Payments</p><p>Fraud Prevention</p><p>Privacy Policy</p></div></div><div className="copyright">© 2025 HomiQ AI. All rights reserved.</div></footer>}
function PropertyCard({p}:{p:any}){return <article className="propertyCard"><div className="photo"><img src={p.image}/><div className="badges"><b>✓ VERIFIED</b><b className="gold">✦ {p.match} MATCH</b><b>◉ 360° VR</b></div></div><div className="cardBody"><div className="priceRow"><strong>{p.price}</strong><span>☆ {p.rating}</span></div><h3>{p.name}</h3><p className="muted">⌖ {p.location}</p><div className="specs"><span>▱ {p.beds}</span><span>□ {p.area}</span></div><button className="details">Details</button></div></article>}
function Home(){return <><Header/><main><section className="hero"><div className="heroText"><small>AI-POWERED REAL ESTATE</small><h1>Find a Home That Feels<br/>Like Yours</h1><p>Seamless matching based on lifestyle analysis, certified property fraud detection, and immersive 360° Virtual Tours.</p><div><button className="goldBtn">Explore Properties</button><button className="outlineBtn">AI Recommendation</button></div></div><img src="/images/home-reference.png"/></section><section className="searchBar"><div><label>LOCATION</label><span>⌖ Beverly Hills, California</span></div><div><label>PROPERTY TYPE</label><span>Luxury Mansion</span></div><div><label>BUDGET RANGE</label><span>$2,500,000 - $5,000,000</span></div><button>⌕ Search</button></section><section className="content"><small className="eyebrow">HOMIQ PICKS</small><div className="sectionTitle"><h2>Featured Smart Homes</h2><span>View All Properties</span></div><div className="grid">{properties.map((p,i)=><PropertyCard p={p} key={i}/>)}</div></section><section className="advantage"><small>INTELLIGENT ASSURANCE</small><h2>The HomiQ Advantage</h2><div className="features"><div><i>♢</i><h3>Certified Property Verification</h3><p>Eliminate fraud. Our proprietary machine learning scans ownership chains, municipal filings, and physical indicators.</p></div><div><i>✦</i><h3>AI Lifestyle Recommendations</h3><p>Go beyond bedrooms. Our AI aligns properties with your daily rhythms, noise preference, sunlight paths, and local vibes.</p></div><div><i>◉</i><h3>True 360° Spatial VR</h3><p>Tour hyper-realistic environments remotely before booking. Explore spaces down to texture scales and sunlight changes.</p></div></div></section><section className="vrPromo"><div><small>NO FLIGHTS REQUIRED</small><h2>Virtual Tours, Real Textures</h2><p>Skip travel friction with high-definition digital twins of elite properties. Place yourself inside the room, experience sunset simulations, and explore adjacent layouts.</p><button className="goldBtn">Launch Demo Tour</button></div><img src="/images/vr-tour.png"/></section><section className="services"><small>END-TO-END COMFORT</small><h2>On-Demand Premium Home Services</h2><div className="serviceGrid"><div><b>1</b><span><strong>Elite Spatial Staging</strong><small>Direct bookings with HomiQ vetted, insured partners.</small></span></div><div><b>2</b><span><strong>Automated Smart Security Install</strong><small>Direct bookings with HomiQ vetted, insured partners.</small></span></div><div><b>3</b><span><strong>Secured Cryptographic Escrow</strong><small>Direct bookings with HomiQ vetted, insured partners.</small></span></div></div></section></main><Footer/></>}
function App(){return <Home/>}
createRoot(document.getElementById('root')!).render(<App/>);
